let fetchFn = globalThis.fetch;
if (!fetchFn) {
  try { fetchFn = require('undici').fetch; } catch { throw new Error('No fetch available. Install undici or use Node 18+'); }
}

// ====== Shortener host list and check util (for fast deeplink optimization) =======
const SHORTENER_HOSTS = [
  // Flipkart shorteners
  'fkrt.it', 'fkrt.cc', 'fktr.in', 'fkrt.to', 'fpkrt.cc', 'zngy.in', 'hyyzo.com', 'extp.in', 'bitlii.com',
  // Flipkart deep-link domain (app deep-links that use JS redirect to the web URL)
  'dl.flipkart.com',
  // Shopsy shorteners (Flipkart's social-commerce platform)
  'bitli.in',
  // App/deep-link shorteners
  'ajioapps.onelink.me', 'ajio.page.link', 'myntr.it',
  // Generic shorteners
  'tinyurl.com', 'bit.ly', 't.co', 'goo.gl', 'ow.ly', 'short.io',
  'rebrand.ly', 'cutt.ly', 'is.gd', 'buff.ly', 'smarturl.it',
  // Affiliate-network tracking domains (intermediate redirect pages that use JS/meta-refresh)
  'clnk.in',          // Cuelinks click tracking
  // Earnko own domain (short URLs generated by the platform)
  'earnko.com'
];
function isShortenerHost(host) {
  host = (host || '').toLowerCase();
  return SHORTENER_HOSTS.some(h => host === h || host.endsWith('.' + h));
}

/**
 * Returns true when the URL path looks like a generic short-code
 * (single path segment, 4-16 alphanumeric characters, no query string).
 * This catches short URLs on unknown hosts that are not in SHORTENER_HOSTS.
 */
function looksLikeShortPath(url) {
  try {
    const u = new URL(url);
    if (u.search) return false; // has query params → likely a real product URL
    const segments = u.pathname.split('/').filter(Boolean);
    if (segments.length !== 1) return false; // must be a single-segment path
    return /^[A-Za-z0-9_-]{3,20}$/.test(segments[0]);
  } catch {
    return false;
  }
}

/**
 * Tries to extract the redirect destination URL that is embedded inside an HTML page.
 * Handles:
 *   - <meta http-equiv="refresh" content="0; url=https://...">
 *   - Common JavaScript redirect patterns:
 *       window.location.href = "..."
 *       window.location = "..."
 *       location.replace("...")
 *       location.href = "..."
 *
 * Returns the extracted absolute URL string, or null if none found.
 */
function extractHtmlRedirect(html, baseUrl) {
  if (!html || typeof html !== 'string') return null;

  // <meta http-equiv="refresh" content="0; url=https://...">  (attribute order may vary)
  const metaPatterns = [
    /<meta[^>]+http-equiv=["']?refresh["']?[^>]+content=["'][^"']*;\s*url=\s*["']?([^"'\s>]+)/i,
    /<meta[^>]+content=["'][^"']*;\s*url=\s*["']?([^"'\s>]+)[^>]*http-equiv=["']?refresh/i,
  ];
  for (const re of metaPatterns) {
    const m = html.match(re);
    if (m?.[1]) {
      try {
        const target = m[1].replace(/&amp;/g, '&').trim();
        const abs = new URL(target, baseUrl).toString();
        if (abs !== baseUrl) return abs;
      } catch { /* skip malformed */ }
    }
  }

  // Common JavaScript redirect patterns — require a minimum URL length of 10 chars to
  // avoid matching variable names or relative paths.
  const MIN_URL_LEN = 10;
  const jsPatterns = [
    new RegExp(`window\\.location\\.href\\s*=\\s*["']([^"']{${MIN_URL_LEN},})["']`, 'i'),
    new RegExp(`window\\.location\\s*=\\s*["']([^"']{${MIN_URL_LEN},})["']`, 'i'),
    new RegExp(`location\\.replace\\s*\\(\\s*["']([^"']{${MIN_URL_LEN},})["']\\s*\\)`, 'i'),
    new RegExp(`location\\.href\\s*=\\s*["']([^"']{${MIN_URL_LEN},})["']`, 'i'),
  ];
  for (const re of jsPatterns) {
    const m = html.match(re);
    if (m?.[1]) {
      try {
        const target = m[1].replace(/&amp;/g, '&').trim();
        const abs = new URL(target, baseUrl).toString();
        if (abs !== baseUrl) return abs;
      } catch { /* skip malformed */ }
    }
  }

  return null;
}

// ======== URL Sanitization, Canonicalization ==========

function sanitizePastedUrl(input) {
  if (input == null) return '';
  let s = String(input).trim();
  s = s.replace(/[\u00A0]/g, ' ');
  s = s.replace(/[\r\n\t]+/g, '');
  s = s.replace(/\s+/g, '');
  s = s.replace(/&amp;/gi, '&');
  if (s && !/^https?:\/\//i.test(s)) s = `https://${s}`;
  return s;
}

function toCanonicalUrl(inputUrl) {
  if (!inputUrl) return '';
  try {
    const u = new URL(inputUrl);
    return u.toString();
  } catch {
    return inputUrl;
  }
}

/**
 * Fix common pasted URL issues that break merchant deeplinks.
 */
function cleanupTrailingUrlJunk(inputUrl) {
  if (!inputUrl) return '';
  let s = String(inputUrl).trim();
  while (s.endsWith('#')) s = s.slice(0, -1);
  while (s.endsWith('?') || s.endsWith('&')) s = s.slice(0, -1);
  return s;
}

function toMerchantSafeUrl(inputUrl) {
  const cleaned = cleanupTrailingUrlJunk(inputUrl);
  if (!cleaned) return '';
  try {
    const u = new URL(cleaned);
    if (u.search === '?') u.search = '';
    return cleanupTrailingUrlJunk(u.toString());
  } catch {
    return cleanupTrailingUrlJunk(cleaned);
  }
}

function normalizeAffiliateInputUrl(input) {
  const cleaned = sanitizePastedUrl(input);
  if (!cleaned) return '';
  return toMerchantSafeUrl(toCanonicalUrl(cleaned));
}

function normalizeHost(inputUrl) {
  try {
    const u = new URL(inputUrl);
    return u.hostname.toLowerCase().replace(/^www\./, '');
  } catch {
    return '';
  }
}

// ======= Platform-specific normalization: Myntra Example =========

function normalizeMyntraUrl(inputUrl) {
  try {
    const host = normalizeHost(inputUrl);
    if (!(host === 'myntra.com' || host.endsWith('.myntra.com') || host === 'myntr.it'))
      return inputUrl;

    const u = new URL(inputUrl);
    const path = u.pathname || '';
    const m = path.match(/\/(\d{6,12})(\/|$)/);
    const productId = m?.[1] || null;
    if (!productId) return inputUrl;

    return `https://www.myntra.com/${productId}`;
  } catch {
    return inputUrl;
  }
}

function makeProviderSafeUrl(inputUrl) {
  const base = toMerchantSafeUrl(toCanonicalUrl(sanitizePastedUrl(inputUrl)));
  const host = normalizeHost(base);

  if (
    host === 'myntra.com' ||
    host.endsWith('.myntra.com') ||
    host === 'myntr.it'
  ) {
    return toMerchantSafeUrl(normalizeMyntraUrl(base));
  }
  return base;
}

function isHttpUrl(url) {
  try {
    const u = new URL(url);
    return u.protocol === 'http:' || u.protocol === 'https:';
  } catch {
    return false;
  }
}

// ==================== ULTRA-FAST FINAL URL RESOLVER =====================

/**
 * Returns the hostname (without leading www.) of a URL string, or '' on error.
 */
function _getHost(url) {
  try { return new URL(url).hostname.toLowerCase().replace(/^www\./, ''); } catch { return ''; }
}

/**
 * Returns true when the given URL still needs further resolution (i.e. it is a
 * shortener page or looks like a short-code path that likely leads to a redirect).
 */
function _needsFurtherResolution(url) {
  const h = _getHost(url);
  return isShortenerHost(h) || looksLikeShortPath(url);
}

/**
 * - Non-shortener hosts (like www.flipkart.com): returns canonical, cleaned, instantly, no network.
 * - Shortener/app hosts (like fkrt.it, ajio.page.link, clnk.in, etc.): follows HTTP redirects first.
 *   If the resolved URL is still on a shortener/short-path domain (meaning the shortener uses a
 *   JavaScript or <meta http-equiv="refresh"> redirect instead of an HTTP 3xx), the response HTML is
 *   parsed for an embedded redirect URL and that URL is followed via one additional HTTP hop.
 * - Timeout is 5 s (increased from 2 s to accommodate the optional second HTTP hop and slow shorteners);
 *   on error/timeout falls back to canonical URL instantly, never hangs.
 */
async function resolveFinalUrl(inputUrl, { timeoutMs = 5000 } = {}) {
  if (!isHttpUrl(inputUrl)) return inputUrl;
  let host = '';
  try { host = new URL(inputUrl).hostname.toLowerCase().replace(/^www\./, ''); } catch {}
  // Direct merchant/product url: return instantly (no network request needed)
  if (!isShortenerHost(host) && !looksLikeShortPath(inputUrl)) return toMerchantSafeUrl(inputUrl);

  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), timeoutMs);

  const headers = {
    'User-Agent': 'Mozilla/5.0 (compatible; EarnkoBot/1.0; +https://earnko.com)'
  };

  try {
    // --- Step 1: Follow HTTP redirects ---
    const res = await fetchFn(inputUrl, {
      method: 'GET',
      redirect: 'follow',
      signal: ctrl.signal,
      headers
    });

    const afterHttp = res?.url || inputUrl;

    // --- Step 2: If still on a shortener / short-path domain, try HTML redirect extraction ---
    // This handles shorteners that redirect via JavaScript or <meta http-equiv="refresh"> instead
    // of HTTP 3xx, and affiliate tracking pages (e.g. clnk.in) that use a JS bounce.
    if (_needsFurtherResolution(afterHttp)) {
      try {
        const contentType = (res.headers?.get?.('content-type') || '').toLowerCase();
        // Treat an absent Content-Type header as HTML, because many URL shorteners
        // omit the header. Non-HTML bodies won't contain any redirect patterns so
        // extractHtmlRedirect will simply return null for them.
        const couldBeHtml = !contentType || contentType.includes('text/html');
        if (couldBeHtml) {
          const html = await res.text();
          const htmlTarget = extractHtmlRedirect(html, afterHttp);
          if (htmlTarget) {
            // Follow the extracted URL one more time via HTTP
            try {
              const res2 = await fetchFn(htmlTarget, {
                method: 'GET',
                redirect: 'follow',
                signal: ctrl.signal,
                headers
              });
              return toMerchantSafeUrl(res2?.url || htmlTarget);
            } catch {
              return toMerchantSafeUrl(htmlTarget);
            }
          }
        }
      } catch { /* ignore body-read errors; fall through to return afterHttp */ }
    }

    return toMerchantSafeUrl(afterHttp);
  } catch {
    // Try HEAD fallback
    try {
      const res2 = await fetchFn(inputUrl, {
        method: 'HEAD',
        redirect: 'follow',
        signal: ctrl.signal,
        headers
      });
      return res2?.url ? toMerchantSafeUrl(res2.url) : toMerchantSafeUrl(inputUrl);
    } catch {
      return toMerchantSafeUrl(inputUrl);
    }
  } finally {
    clearTimeout(timer);
  }
}

module.exports = {
  sanitizePastedUrl,
  toCanonicalUrl,
  normalizeAffiliateInputUrl,
  normalizeMyntraUrl,
  makeProviderSafeUrl,
  resolveFinalUrl,
  // for custom logic/testing
  toMerchantSafeUrl,
  cleanupTrailingUrlJunk,
  isShortenerHost,
  looksLikeShortPath,
  extractHtmlRedirect
};