const express = require('express');
const mongoose = require('mongoose');
const { auth } = require('../../middleware/auth');
const ShortUrl = require('../../models/ShortUrl');

const router = express.Router();

/**
 * GET /api/user/short-urls
 * Returns user's latest commission-safe short URLs (the same ones generated by /api/affiliate/link-from-url)
 *
 * Query:
 *  - page (default 1)
 *  - limit (default 10, max 50)
 *
 * Response:
 *  success: true
 *  data: {
 *    items: [{ code, shortUrl, slug, provider, clickId, createdAt }],
 *    total,
 *    currentPage,
 *    totalPages
 *  }
 */
router.get('/', auth, async (req, res) => {
  try {
    const pageNum = Math.max(parseInt(req.query?.page, 10) || 1, 1);
    const limitNum = Math.min(Math.max(parseInt(req.query?.limit, 10) || 10, 1), 50);

    const userId = req.user?._id;
    if (!userId || !mongoose.Types.ObjectId.isValid(userId)) {
      return res.status(401).json({ success: false, message: 'Unauthorized' });
    }

    const filter = { user: userId };

    const base =
      (process.env.PUBLIC_SITE_URL || process.env.FRONTEND_URL || 'http://localhost:3000').replace(/\/+$/, '');

    const [rows, total] = await Promise.all([
      ShortUrl.find(filter)
        .sort({ createdAt: -1 })
        .skip((pageNum - 1) * limitNum)
        .limit(limitNum)
        .lean(),
      ShortUrl.countDocuments(filter),
    ]);

    const items = rows.map((r) => ({
      code: r.code,
      shortUrl: `${base}/r/${r.code}`, // ✅ commission-safe short URL
      slug: r.slug || '',
      provider: r.provider || '',
      clickId: r.clickId || '',
      createdAt: r.createdAt,
    }));

    return res.json({
      success: true,
      data: {
        items,
        total,
        currentPage: pageNum,
        totalPages: Math.ceil(total / limitNum),
      },
    });
  } catch (err) {
    console.error('user short-urls error', err);
    return res.status(500).json({ success: false, message: 'Server error' });
  }
});

module.exports = router;